name: Sync Crowdin translations

on:
  push:
    branches:
      - "flutter"
    paths:
      - "assets/i18n/en_US.json"
      - ".github/workflows/crowdin.yml"
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:

jobs:
  sync-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Crowdin
        uses: crowdin/github-action@v1
        with:
          config: crowdin.yml
          upload_sources: true
          upload_translations: false
          download_translations: true
          push_translations: true
          create_pull_request: false
          localization_branch_name: i18n_flutter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID  }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      # commented due to Manager not being ready for the translated files to be in the main branch
      # - name: GitHub is so dumb i just cant
      #   run: |
      #     sudo chmod -R ugo+rwX .

      # - name: Merge
      #   run: |
      #     git checkout flutter
      #     git add *
      #     git merge i18n_flutter
      #     git push
